### ISSUE TITLE
ImportError: cannot import name 'get_paths_extents' from 'matplotlib.path'

### ISSUE THREAD

**Issue by JakkuSakura** [karlwessel/mplopengl#15]
Removing the line in renderergl.py makes it work again.
```python
18: from matplotlib.path import get_paths_extents
```
matplotlib version is 3.3.2

**Comment by karlwessel** [comment]
I could have seen this coming (see issue #8).

I guess I can't just remove that line since the method is actually used. It needs to be replaced by `get_path_collection_extend`.

Thanks for the issue, I'll take a look at it.

**Comment by karlwessel** [comment]
For now I fixed it by removing support for clip_paths (which weren't implemented correctly anyway).
